// <auto-generated />
namespace COF.DataAccess.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201908100849196_EditDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
