// <auto-generated />
namespace COF.DataAccess.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddVouchourSupportDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddVouchourSupportDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201909031820024_AddVouchourSupportDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
