// <auto-generated />
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression

namespace COF.DataAccess.EF.Repositories
{
	using COF.DataAccess.EF.Infrastructure;
	using Models = COF.DataAccess.EF.Models;
	
	public partial interface IShopRepository : IRepository<Models.Shop> {}
	
	public partial class ShopRepository : EFRepository<Models.Shop>, IShopRepository { public ShopRepository(EFContext context) : base(context){} }
	
	public partial interface ITableRepository : IRepository<Models.Table> {}
	
	public partial class TableRepository : EFRepository<Models.Table>, ITableRepository { public TableRepository(EFContext context) : base(context){} }
	
	public partial interface IProductRepository : IRepository<Models.Product> {}
	
	public partial class ProductRepository : EFRepository<Models.Product>, IProductRepository { public ProductRepository(EFContext context) : base(context){} }
	
	public partial interface IOrderRepository : IRepository<Models.Order> {}
	
	public partial class OrderRepository : EFRepository<Models.Order>, IOrderRepository { public OrderRepository(EFContext context) : base(context){} }
}

